version: '3.8'
services:
  # product-database:
  #   image: mysql:8.0.42
  #   container_name: product-database
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "${DB_PORT}:3306"
  #   networks:
  #     - product-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    # depends_on:
    #   - product-database
    command: sh ./start.sh
    ports:
      - "8000:80"
    networks:
      - product-network

volumes:
  mysql-data:
networks:
  product-network:

